### ISSUE TITLE
thread 'main' panicked at src/ffetch.rs:847:43: called `Result::unwrap()` on an `Err` value: XcbConnError(ClosedParseErr) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Aborted                    (core dumped) ffetch

### ISSUE THREAD

**Issue by ket000** [0l3d/ffetch#2]
Getting this in cachyos after installing it.

paru ffetch

thread 'main' panicked at src/ffetch.rs:847:43:
called `Result::unwrap()` on an `Err` value: XcbConnError(ClosedParseErr)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted                    (core dumped) ffetch

**Comment by 0l3d** [comment]
Can you try it now? An old dependency required a few system libraries, but I replaced it with another one.

Old: 
<img width="161" height="161" alt="Image" src="https://github.com/user-attachments/assets/08cf16ec-c225-4aa2-9dcb-a37983a3efce" />

New:
<img width="169" height="100" alt="Image" src="https://github.com/user-attachments/assets/b7924e0d-1b0d-4ab8-af7b-335564c0a1e8" />

Also, I updated the release I published on the AUR

Thanks for your notification. If the issue isnt resolved, you can reply.

**Comment by ket000** [comment]
Getting this now

=> Making package: ffetch 0.2.16-1 (Tue 02 Sep 2025 11:01:11 PM EDT)
==> Retrieving sources...
  -> Downloading ffetch-v0.2.16-linux-x86_64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  252k  100  252k    0     0   772k      0 --:--:-- --:--:-- --:--:--  772k
==> Validating source files with sha256sums...
    ffetch-v0.2.16-linux-x86_64.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'ffetch-0.2.16-1': 
error: packages failed to build: ffetch-0.2.16-1

**Comment by ket000** [comment]
I tried installing using below

paru -S --mflags "--skipinteg" ffetch
It installed but still getting the error

thread 'main' panicked at src/ffetch.rs:945:18:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted                    (core dumped) ffetch

**Comment by 0l3d** [comment]
https://github.com/0l3d/ffetch?tab=readme-ov-file#%EF%B8%8F-all-possible-problems-and-solutions

Maybe this link could help, but do you have `xrandr` installed? its required to retrieve monitor information.

**Comment by 0l3d** [comment]
i have added a new update to the repo, aur will be updated, xrandr is no longer required

**Comment by ket000** [comment]
The latest version fixed the issue I originally Reported. My linux is a virutal machine hosted inside vmware workstaiton pro and is CachyOS. It now gives the below message

Primary: (Virtual-1): Failed to parse EDID

Also on my black window, the word Primary is not very clear. 
I think the default color should be changed for the Headings.

**Comment by 0l3d** [comment]
i've committed new bug fixes and created a new release, the aur package will likely be updated soon (i'm not the main maintainer of the aur package).
if you want to try it out immediately, you can download the release and report any issues you encounter.


Update information:
if get_monitor fails, it will try to use `xrandr` as a fallback.
if you're using virtual machine, please make sure `xrandr` is installed.

Additionally, ffetch has a configurable config file
You can check this link to see what you can customize: [F-Fetch Configuration & Examples](https://github.com/0l3d/ffetch/tree/master?tab=readme-ov-file#f-fetch-configuration--examples.)
You can change the colors directly in the config file and tweak it however you like, you’re free to customize it as you wish.
